### ISSUE TITLE
Flutter工程如何直接在Flutter中初始化？

### ISSUE THREAD

**Issue by li-xiaojun** [bytedance/rangers_applog_flutter_plugin#1]
Flutter工程如何直接在Flutter中初始化？
既然都使用Flutter了，为啥还要分别在android和iOS中进行代码初始化，作为一个Flutter开发者，对android和iOS不熟悉。希望直接在Flutter中初始化。

**Comment by zlrs** [comment]
1. 在原生环境初始化，是因为SDK对初始化的时机要求比较高，需要尽可能早。并且在原生集成/初始化可以给用户提供更高的自由度。否则可能会丢失应用启动等事件，影响日活等数据，对数据分析有不利影响。
2. 可以参考Readme和Example来在原生环境中初始化。
